# Generated by Django 4.1.7 on 2023-04-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_comment_post_id_remove_comment_username_and_more'),
    ]

    operations = [

    ]
