# Generated by Django 4.1.7 on 2023-04-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tag_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='radius',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
