# Generated by Django 4.1.7 on 2023-04-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_location_radius'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='location',
        ),
        migrations.AddField(
            model_name='story',
            name='locations',
            field=models.ManyToManyField(blank=True, to='core.location'),
        ),
    ]
