# Generated by Django 4.1.7 on 2023-04-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_file_remove_story_image_story_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date_format',
            field=models.IntegerField(choices=[(1, 'Exact Date'), (2, 'Range of Dates'), (3, 'Decade')], default=1),
        ),
        migrations.AlterField(
            model_name='story',
            name='decade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='locations',
            field=models.ManyToManyField(to='core.location'),
        ),
    ]
