# Generated by Django 4.1.7 on 2023-04-19 12:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_story_date_format_alter_story_decade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='area',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
