# Generated by Django 4.1.7 on 2023-05-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_location_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
