# Generated by Django 4.1.7 on 2023-05-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_story_no_of_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_liked_by_current_user',
            field=models.BooleanField(default=False),
        ),
    ]
