# Generated by Django 4.1.7 on 2023-05-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_story_is_liked_by_current_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='no_of_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=255),
        ),
    ]
