# Generated by Django 4.1.7 on 2023-05-16 11:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_story_no_of_comments_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
