# Generated by Django 4.1.7 on 2023-05-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_story_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='exact_date_and_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='date_format',
            field=models.IntegerField(choices=[(1, 'Exact Date'), (2, 'Range of Dates'), (3, 'Decade'), (4, 'Exact Date and Time')], default=1),
        ),
    ]
